In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\MACHINE LEARNING PROJECTS\Navie Bayes Algorithsim Movie Algorithsim\IMDB Dataset.csv")
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
import re

def clean(text):
    text = str(text).lower()
    text = re.sub(r'<.*?>', '', text)           # HTML tags hatao (<br/> etc)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)  # URLs hatao
    text = re.sub(r'[^\w\s]', '', text)         # Punctuation hatao
    text = re.sub(r'\s+', ' ', text)            # Extra spaces hatao
    text = text.strip()
    return text

In [4]:
df['review'] = df['review'].apply(clean)

In [5]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [6]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import nltk

In [7]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\great\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [8]:
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

In [9]:
keep_words = {'not', 'no', 'never', 'but', 'however', 'although'}
stop_words = stop_words - keep_words

In [10]:
def clean(text):
    text = str(text).lower()
    text = re.sub(r'<.*?>', ' ', text)              # HTML tags
    text = re.sub(r'https?://\S+|www\.\S+', '', text)  # URLs
    text = re.sub(r'[^\w\s]', '', text)             # Punctuation
    text = re.sub(r'\d+', '', text)                 # Numbers
    text = re.sub(r'\s+', ' ', text).strip()        # Extra spaces
    
    # Stopwords remove + Stemming
    words = text.split()
    #ords = [ps.stem(w) for w in words if w not in stop_words]
    
    return ' '.join(words)

In [11]:
df['review'] = df['review'].apply(clean)

In [12]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [13]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
encoder = LabelEncoder()

In [16]:
df['sentiment']=encoder.fit_transform(df.sentiment)

In [17]:
df

                                                  review  sentiment
0      one of the other reviewers has mentioned that ...          1
1      a wonderful little production the filming tech...          1
2      i thought this was a wonderful way to spend ti...          1
3      basically theres a family where a little boy j...          0
4      petter matteis love in the time of money is a ...          1
...                                                  ...        ...
49995  i thought this movie did a down right good job...          1
49996  bad plot bad dialogue bad acting idiotic direc...          0
49997  i am a catholic taught in parochial elementary...          0
49998  im going to have to disagree with the previous...          0
49999  no one expects the star trek movies to be high...          0

[50000 rows x 2 columns]

In [18]:
x = df['review']
x

0        one of the other reviewers has mentioned that ...
1        a wonderful little production the filming tech...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    im going to have to disagree with the previous...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [19]:
y = df['sentiment']
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 50000, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.40,random_state=0)

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer(stop_words='english')
X_train_vec = vector.fit_transform(x_train)
X_test_vec = vector.transform(x_test)

In [22]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_vec,y_train)

MultinomialNB()

In [23]:
y_pred = model.predict(X_test_vec)

In [24]:
y_pred_prob = model.predict(X_test_vec)
y_pred_prob

array([1, 0, 1, ..., 0, 0, 0], shape=(20000,))

In [25]:
len(y_pred)

20000

In [26]:
from sklearn.metrics import confusion_matrix,accuracy_score

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[8757 1311]
 [1637 8295]]
0.8526

In [45]:
t= 'one reviewers mentioned watching oz episode youll hooked right exactly happened first thing struck oz brutality unflinching scenes violence set right word go trust not show faint hearted timid show pulls no punches regards drugs sex violence hardcore classic use word called oz nickname given oswald maximum security state penitentary focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy not high agenda em city home manyaryans muslims gangstas latinos christians italians irish moreso scuffles death stares dodgy dealings shady agreements never far away would say main appeal show due fact goes shows wouldnt dare forget pretty pictures painted mainstream audiences forget charm forget romanceoz doesnt mess around first episode ever saw struck nasty surreal couldnt say ready but watched developed taste oz got accustomed high levels graphic violence not violence but injustice crooked guards wholl sold nickel inmates wholl kill order get away well mannered middle class inmates turned prison bitches due lack street skills prison experience watching oz may become comfortable uncomfortable viewingthats get touch darker side'
text1 = vector.transform([t])
prd = model.predict(text1)
original = encoder.inverse_transform(prd)
original[0]

'positive'

In [28]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\great\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [29]:
df = pd.read_csv(r"C:\MACHINE LEARNING PROJECTS\Navie Bayes Algorithsim Movie Algorithsim\IMDB Dataset.csv")
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [30]:
stop_words = set(stopwords.words('english'))
keep_words = {'not', 'no', 'never', 'but'}  # sentiment ke liye
stop_words = stop_words - keep_words

In [31]:
def clean(text):
    text = str(text).lower()
    text = re.sub(r'<.*?>', ' ', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[^\x00-\x7F]+', '', text) 
    text = re.sub(r'\s+', ' ', text).strip()
    words = [w for w in text.split() if w not in stop_words]
    return ' '.join(words)

In [32]:
df['review'] = df['review'].apply(clean)

In [33]:
encoder = LabelEncoder()
df['sentiment'] = encoder.fit_transform(df['sentiment'])

In [34]:
df

                                                  review  sentiment
0      one reviewers mentioned watching oz episode yo...          1
1      wonderful little production filming technique ...          1
2      thought wonderful way spend time hot summer we...          1
3      basically theres family little boy jake thinks...          0
4      petter matteis love time money visually stunni...          1
...                                                  ...        ...
49995  thought movie right good job wasnt creative or...          1
49996  bad plot bad dialogue bad acting idiotic direc...          0
49997  catholic taught parochial elementary schools n...          0
49998  im going disagree previous comment side maltin...          0
49999  no one expects star trek movies high art but f...          0

[50000 rows x 2 columns]

In [35]:
X_train, X_test, y_train, y_test = train_test_split(df['review'], df['sentiment'], test_size=0.2, random_state=42)

In [36]:
vector = TfidfVectorizer(
    max_features=150000,     
    ngram_range=(1, 3),      
    sublinear_tf=True,
    min_df=2,
    max_df=0.95
)

In [37]:
X_train_vec = vector.fit_transform(X_train)
X_test_vec = vector.transform(X_test)

In [38]:
model = MultinomialNB(alpha=0.9) 
model.fit(X_train_vec, y_train)

MultinomialNB(alpha=0.9)

In [39]:
y_pred = model.predict(X_test_vec)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[4406  555]
 [ 527 4512]]
Accuracy: 0.8918

In [40]:
t='one of the other reviewers has mentioned that'
text1 = vector.transform([t])
prd = model.predict(text1)
original = encoder.inverse_transform(prd)
original[0]

'negative'

In [44]:
df.to_csv(r"C:\Users\great\Downloads\label.csv")